services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: yourAccountant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
        - LANG=ru_RU.UTF-8
        - LANGUAGE=ru_RU:ru
        - LC_ALL=ru_RU.UTF-8
    ports:
      - "15432:5432"


  web:
    build: .
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:

