# Generated by Django 5.1.1 on 2024-09-25 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_income_category_remove_income_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.subcategory'),
        ),
    ]
