# Generated by Django 5.1.1 on 2024-09-25 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_subcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity_type',
            field=models.CharField(choices=[('шт', 'Шт'), ('кг', 'Кг'), ('л', 'Л'), ('см', 'СМ')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.subcategory'),
        ),
    ]
