# Generated by Django 5.1.1 on 2024-09-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_quantity_transaction_quantity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quantity_type',
            field=models.CharField(choices=[('шт', 'шт'), ('кг', 'кг'), ('л', 'л'), ('см', 'см')], max_length=4, null=True),
        ),
    ]
