# Generated by Django 5.1.1 on 2024-09-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quantity_type',
            field=models.CharField(blank=True, choices=[('шт', 'шт'), ('кг', 'кг'), ('л', 'л'), ('см', 'см')], max_length=4, null=True),
        ),
    ]
