# Generated by Django 5.1.1 on 2024-09-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_category_name_alter_subcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
