# Generated by Django 5.1.1 on 2024-10-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('opera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='htmx_test.opera')),
            ],
        ),
    ]
