# Generated by Django 5.1.1 on 2024-10-04 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('soprano', 'Soprano'), ('tenor', 'Tenor'), ('baritone', 'Baritone'), ('bass', 'Bass')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmx_test.voice')),
            ],
        ),
    ]
