# Generated by Django 5.1.1 on 2024-10-04 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmx_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='voice',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htmx_test.singer')),
            ],
        ),
        migrations.DeleteModel(
            name='Voice',
        ),
    ]
