# Generated by Django 5.1.1 on 2024-10-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmx_test', '0002_alter_singer_voice_opera_delete_voice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opera',
            name='singer',
        ),
        migrations.AddField(
            model_name='singer',
            name='opera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='htmx_test.opera'),
        ),
    ]
